name: Telegram ChatGPT-3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '* */6 * * *'
  workflow_dispatch:

env:
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install OpenAI package
        run: |
          pip install openai
      - name: Install Telegram package
        run: |
          pip install python-telegram-bot
      - name: Get response from OpenAI
        run: |
          response=$(openai api completions.create --model "text-davinci-002" --prompt "Hello, can you help me with this?" --temperature 0.7)
          echo "::set-output name=response::$(echo $response | jq '.choices[0].text' -r)"
        id: response
      - name: Send message to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ env.CHAT_ID }}
        run: |
          python send_message.py "${{ steps.response.outputs.response }}"
